---
abstract: 'Tool to switch stow dist for command.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Stow-Switch
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Curses::UI: 0
  Encode: 0
  Error::Pure: 0.15
  File::Find::Rule: 0
  File::Path: 0
  File::Spec::Functions: 0
  Getopt::Std: 0
  IO::Barf: 0
  List::MoreUtils: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-Stow-Switch/issues
  homepage: https://github.com/michal-josef-spacek/App-Stow-Switch
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-Stow-Switch
version: '0.01'
